routes/admin.php
<?php
/*
|--------------------------------------------------------------------------
| Web Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
Route::group([
    'prefix' => 'auth',
    'as'     => 'auth.',
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('postlogin');
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::post('password/reset', 'ForgotPasswordController@reset')->name('password.update');

    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register')->name('postregister');

});

Route::group([
    'middleware' => 'auth.admin',
], function () {
    Route::get('/', function () {
        return redirect()->route('admin.home');
    });

    Route::get('/home', function () {
        return view('admin.home');
    })->name('home');

    Route::group(
        [
            'prefix' => 'image',
            'as'     => 'image.',
        ],
        function () {
            Route::post('uploadmultiple/{type?}', 'ImageController@uploadImageMultiple')->name('uploadmultiple');
            Route::post('uploadone/{type?}', 'ImageController@uploadImageOne')->name('uploadone');
            Route::post('removebysrc', 'ImageController@removeBySrc')->name('removebysrc');
        }
    );

    Route::group(
        [
            'prefix'     => 'blogcategory',
            'as'         => 'blogcategory.',
            'middleware' => ['permission:blog-category-control'],
        ],
        function () {
            Route::get('index', 'BlogCategoryController@index')->name('index');
            Route::get('show/{id}', 'BlogCategoryController@show')->name('show');
            Route::get('create', 'BlogCategoryController@create')->name('create');
            Route::post('store', 'BlogCategoryController@store')->name('store');
            Route::get('edit/{id}', 'BlogCategoryController@edit')->name('edit');
            Route::put('update/{id}', 'BlogCategoryController@update')->name('update');
            Route::delete('destroy/{id}', 'BlogCategoryController@destroy')->name('destroy');
            Route::put('restore/{id}', 'BlogCategoryController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix' => 'blogbanner',
            'as'     => 'blogbanner.',
        ],
        function () {
            Route::post('update_position','BlogBannerController@updatePosition')->name('update_position');
            Route::get('index', 'BlogBannerController@index')->name('index');
            Route::get('show/{id}', 'BlogBannerController@show')->name('show');
            Route::get('create', 'BlogBannerController@create')->name('create');
            Route::post('store', 'BlogBannerController@store')->name('store');
            Route::get('edit/{id}', 'BlogBannerController@edit')->name('edit');
            Route::put('update/{id}', 'BlogBannerController@update')->name('update');
            Route::delete('destroy/{id}', 'BlogBannerController@destroy')->name('destroy');
            Route::put('restore/{id}', 'BlogBannerController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix' => 'blog',
            'as'     => 'blog.',
        ],
        function () {
            Route::get('index', 'BlogController@index')->name('index')->middleware('permission:blog-show');
            Route::get('show/{id}', 'BlogController@show')->name('show')->middleware('permission:blog-show');
            Route::get('create', 'BlogController@create')->name('create')->middleware('permission:blog-create');
            Route::post('store', 'BlogController@store')->name('store')->middleware('permission:blog-create');
            Route::get('edit/{id}', 'BlogController@edit')->name('edit')->middleware('permission:blog-edit');
            Route::put('update/{id}', 'BlogController@update')->name('update')->middleware('permission:blog-edit');
            Route::delete('destroy/{id}', 'BlogController@destroy')->name('destroy')->middleware('permission:blog-remove');
            Route::put('restore/{id}', 'BlogController@restore')->name('restore')->middleware('permission:blog-remove');
        }
    );

    Route::group(
        [
            'prefix'     => 'productcategory',
            'as'         => 'productcategory.',
            'middleware' => ['permission:product-category-control'],
        ],
        function () {
            Route::get('index', 'ProductCategoryController@index')->name('index');
            Route::get('show/{id}', 'ProductCategoryController@show')->name('show');
            Route::get('create', 'ProductCategoryController@create')->name('create');
            Route::post('store', 'ProductCategoryController@store')->name('store');
            Route::get('edit/{id}', 'ProductCategoryController@edit')->name('edit');
            Route::put('update/{id}', 'ProductCategoryController@update')->name('update');
            Route::delete('destroy/{id}', 'ProductCategoryController@destroy')->name('destroy');
            Route::put('restore/{id}', 'ProductCategoryController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix' => 'product',
            'as'     => 'product.',
        ],
        function () {
            Route::get('index', 'ProductController@index')->name('index')->middleware('permission:product-show');
            Route::get('show/{id}', 'ProductController@show')->name('show')->middleware('permission:product-show');
            Route::get('create', 'ProductController@create')->name('create')->middleware('permission:product-create');
            Route::post('store', 'ProductController@store')->name('store')->middleware('permission:product-create');
            Route::get('edit/{id}', 'ProductController@edit')->name('edit')->middleware('permission:product-edit');
            Route::put('update/{id}', 'ProductController@update')->name('update')->middleware('permission:product-edit');
            Route::delete('destroy/{id}', 'ProductController@destroy')->name('destroy')->middleware('permission:product-remove');
            Route::put('restore/{id}', 'ProductController@restore')->name('restore')->middleware('permission:product-remove');
        }
    );

    Route::group(
        [
            'prefix' => 'slider',
            'as'     => 'slider.',
        ],
        function () {
            Route::post('update_position','SliderController@updatePosition')->name('update_position');
            Route::get('index', 'SliderController@index')->name('index');
            Route::get('show/{id}', 'SliderController@show')->name('show');
            Route::get('create', 'SliderController@create')->name('create');
            Route::post('store', 'SliderController@store')->name('store');
            Route::get('edit/{id}', 'SliderController@edit')->name('edit');
            Route::put('update/{id}', 'SliderController@update')->name('update');
            Route::delete('destroy/{id}', 'SliderController@destroy')->name('destroy');
            Route::put('restore/{id}', 'SliderController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix'     => 'user',
            'as'         => 'user.',
            'middleware' => ['permission:user-control'],
        ],
        function () {
            Route::get('index', 'UserController@index')->name('index');
            Route::get('show/{id}', 'UserController@show')->name('show');
            Route::get('create', 'UserController@create')->name('create');
            Route::post('store', 'UserController@store')->name('store');
            Route::get('edit/{id}', 'UserController@edit')->name('edit');
            Route::get('edit-permission/{id}', 'UserController@editPermission')->name('edit_permission');
            Route::put('update-permission/{id}', 'UserController@updatePermission')->name('update_permission');
            Route::put('update/{id}', 'UserController@update')->name('update');
            Route::delete('destroy/{id}', 'UserController@destroy')->name('destroy');
            Route::put('restore/{id}', 'UserController@restore')->name('restore');
            Route::put('approve/{id}', 'UserController@approve')->name('approve');
        }
    );


    Route::group(
        [
            'prefix'     => 'brandcategory',
            'as'         => 'brandcategory.',
        ],
        function () {
            Route::get('index', 'BrandCategoryController@index')->name('index');
            Route::get('show/{id}', 'BrandCategoryController@show')->name('show');
            Route::get('create', 'BrandCategoryController@create')->name('create');
            Route::post('store', 'BrandCategoryController@store')->name('store');
            Route::get('edit/{id}', 'BrandCategoryController@edit')->name('edit');
            Route::put('update/{id}', 'BrandCategoryController@update')->name('update');
            Route::delete('destroy/{id}', 'BrandCategoryController@destroy')->name('destroy');
            Route::put('restore/{id}', 'BrandCategoryController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix' => 'brand',
            'as'     => 'brand.',
        ],
        function () {
            Route::get('index', 'BrandController@index')->name('index');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('error/{code}', function ($code) {
    return view('errors.error', compact('code'));
})->name('error');

Route::group([
	'as' =>'user.',
    'namespace' => 'User',
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('doanh-nghiep', 'HomeController@business')->name('business');
    Route::get('ve-chung-toi', 'HomeController@aboutus')->name('aboutus');
    Route::get('faq', 'HomeController@faq')->name('faq');
    Route::get('lien-he', 'HomeController@contact')->name('contact');
    Route::post('lien-he/{type}', 'HomeController@submitContact')->name('submitContact');
    Route::get('blog', 'HomeController@blog')->name('blog');
    Route::get('blog/article/{slug}_{id}', 'HomeController@blogDetail')->name('blog.detail');
    Route::get('blog/category/{slug}_{id}', 'HomeController@blogCategory')->name('blog.category');
});

app/Models/Blog.php
<?php

namespace App\Models;

use App\Models\BaseModel;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class Blog extends BaseModel
{
    use SoftDeletes;

    protected $fillable = [
        'blog_category_id',
        'title',
        'slug',
        'content',
        'public_at',
        'status',
        'tags',
        'popular',
    ];

    protected $appends = [
        'status_text','image_frist'
    ];

    public function setTagsAttribute($value)
    {
        $this->attributes['tags'] = "," . $value . ",";
    }

    public function getTagsAttribute()
    {
        return rtrim(ltrim($this->attributes['tags'], ','), ',');
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug']  = str_slug($value);
    }

    public function getStatusTextAttribute()
    {
        return $this->status == 2 ? "Hide" : "Show";
    }

    public function getPopularTextAttribute()
    {
        return $this->popular == 1 ? "No" : "Yes";
    }

    public function getPublicAtShowAttribute()
    {
        return date("d-m-Y", strtotime($this->public_at));
    }

    public function setPublicAtAttribute($value)
    {
        $this->attributes['public_at'] = Carbon::parse($value);
    }

    public function getImageFirstAttribute()
    {
        return $this->images->where('status',2)->first()->src;
    }

    public function images()
    {
        return $this->morphMany(Images::class, 'imagetable');
    }

    public function category()
    {
        return $this->belongsTo('App\Models\BlogCategory', 'blog_category_id');
    }

    public function scopeSearchTags($query, $tags = [])
    {
        if (is_array($tags)) {
            foreach ($tags as $tag) {
                $query->orWhere('tags', 'like', '%,' . $tag . ".%");
            }
        }
    }

    public function scopeGetPopular($query)
    {
        return $query->wherePopular(2);
    }

    public function scopeUserGetList($query)
    {
        return $query->whereStatus(1)
        ->whereDate('public_at', '<=', Carbon::now())
        ->orderBy('public_at', 'DESC');
    }
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\BlogRequest;
use App\Services\BlogCategoryService;
use App\Services\BlogService;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    protected $blogService;
    protected $blogCategoryService;

    public function __construct(BlogService $blogService, BlogCategoryService $blogCategoryService)
    {
        $this->blogService         = $blogService;
        $this->blogCategoryService = $blogCategoryService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = $this->blogService->getList(true);
        return view('admin.blog.blog.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = $this->blogCategoryService->getListOnlyChildren();
        return view('admin.blog.blog.form', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogRequest $request)
    {
        $this->blogService->storeOrUpdate($request->all());
        return redirect()->route('admin.blog.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = $this->blogService->findById($id);
        return view('admin.blog.blog.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog       = $this->blogService->findById($id);
        $categories = $this->blogCategoryService->getListOnlyChildren();
        return view('admin.blog.blog.form', compact('categories', 'blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogRequest $request, $id)
    {
        $this->blogService->storeOrUpdate($request->all(), $id);
        return redirect()->route('admin.blog.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->blogService->destroyById($id);
        return redirect()->route('admin.blog.index');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {   
        $this->blogService->restoreById($id);
        return redirect()->route('admin.blog.index');
    }
}

resources/views/user/mosaic/page/blog/detail.blade.php
@extends('user.mosaic.layout.master',[
    'title'=>'| Tin Tức - Ưu Đãi | Utop',
    'menu' => 'blog',
])
@section('content')
<section class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <h1 class="mb-2 bread">{{$blog->title}}</h1>
        <p class="breadcrumbs"><span class="mr-2"><a href="{{route('home')}}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="{{route('blog')}}">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>{{$blog->title}} <i class="ion-ios-arrow-forward"></i></span></p>
      </div>
    </div>
  </div>
</section>
    
<section class="ftco-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 ftco-animate">
          {!!nl2br($blog->content)!!}
          <div class="tag-widget post-tag-container mb-5 mt-5">
            <div class="tagcloud">
              @foreach(explode(",", $blog->tags) as $keyTag => $valueTag)
              <a href="#" class="tag-cloud-link">{{$valueTag}}</a>
              @endforeach
            </div>
          </div>
          <section class="ftco-section ftco-no-pb">
              <div class="container-wrap">
                <div class="row no-gutters">
                  @foreach($blog->images as $keyImage =>$valueImage)
                  <div class="col-md-6 col-lg-3 ftco-animate">
                    <div class="project">
                      <img src="{{url($valueImage->src)}}" class="img-fluid" alt="Colorlib Template">
                      <div class="text">
                        <span>{{$blog->title}}</span>
                        <h3>Hình số {{$keyImage +1}}</h3>
                      </div>
                      <a href="{{url($valueImage->src)}}" class="icon image-popup d-flex justify-content-center align-items-center">
                        <span class="icon-expand"></span>
                      </a>
                    </div>
                  </div>
                  @endforeach
                </div>
              </div>
            </section>
        </div> <!-- .col-md-8 -->
        @include('user.mosaic.page.blog.menu_right')
      </div><!-- END COL -->
    </div>
</section>
@stop

resources/views/user/mosaic/page/blog/index.blade.php
@extends('user.mosaic.layout.master',[
    'title'=>'Tin Tức - Ưu Đãi',
    'menu' => 'blog',
])
@section('content')
<section class="hero-wrap hero-wrap-2" style="background-image: url('/mosaic/images/banner_utop.png');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <h1 class="mb-2 bread">Tin Tức - Ưu Đãi</h1>
        <p class="breadcrumbs"><span class="mr-2"><a href="/">Trang Chủ <i class="ion-ios-arrow-forward"></i></a></span> <span>Tin Tức - Ưu Đãi <i class="ion-ios-arrow-forward"></i></span></p>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="row">
          @foreach($blogs as $keyBlog => $valueBlog)
          <div class="col-md-6 ftco-animate">
            <div class="blog-entry">
              <a href="{{route('blog.detail',['slug'=>$valueBlog->slug,'id'=>$valueBlog->id])}}" class="block-20" style="background-image: url('{{$valueBlog->image_first}}');">
              </a>
              <div class="text d-flex py-4">
                <div class="meta mb-3">
                  <div><a href="#">{{$valueBlog->public_at_show}}</a></div>
                </div>
                <div class="desc pl-3">
                  <h3 class="heading"><a href="{{route('blog.detail',['slug'=>$valueBlog->slug,'id'=>$valueBlog->id])}}">{{$valueBlog->title}}</a></h3>
                </div>
              </div>
            </div>
          </div>
          @endforeach
        </div>
        <div class="row no-gutters my-5">
          <div class="col text-center">
            <div class="block-27">
              {{ $blogs->appends($_GET)->links("user.mosaic.layout.paginate") }}
            </div>
          </div>
        </div>
      </div>
    
      @include('user.mosaic.page.blog.menu_right')
      </div><!-- END COL -->
    </div>
  </div>
</section>
@stop

resources/views/user/mosaic/page/blog/menu_right.blade.php
<div class="col-lg-4 sidebar ftco-animate">
<div class="sidebar-box ftco-animate">
  <h3>Danh mục</h3>
  <ul class="categories">
    @foreach($categories as $keyCategory => $category)
    <li><a href="#">{{$category->name}}</a></li>
    @endforeach
  </ul>
</div>

<div class="sidebar-box ftco-animate">
  <h3>Popular Articles</h3>
  @foreach($popularBlogs as $keyPopularBlog => $popularBlog)
  <div class="block-21 mb-4 d-flex">
    <a class="blog-img mr-4" style="background-image: url({{$popularBlog->image_first}});"></a>
    <div class="text">
      <h3 class="heading"><a href="#">{{$popularBlog->title}}</a></h3>
      <div class="meta">
        <div><a href="#"><span class="icon-calendar"></span> {{$popularBlog->public_at_show}}</a></div>
      </div>
    </div>
  </div>
  @endforeach
</div>

{{-- <div class="sidebar-box ftco-animate">
  <h3>Tag Cloud</h3>
  <ul class="tagcloud m-0 p-0">
    <a href="#" class="tag-cloud-link">House</a>
    <a href="#" class="tag-cloud-link">Office</a>
    <a href="#" class="tag-cloud-link">Land</a>
    <a href="#" class="tag-cloud-link">Building</a>
    <a href="#" class="tag-cloud-link">Table</a>
    <a href="#" class="tag-cloud-link">Intrior</a>
    <a href="#" class="tag-cloud-link">Exterior</a>
  </ul>
</div> --}}


<div class="sidebar-box ftco-animate">
  <h3>Utop</h3>
  <p>Utop là ứng dụng tích và đổi quà điện tử, cho phép bạn tích lũy điểm hoặc trực tiếp nạp điểm để đổi quà và tiêu điểm tại hàng trăm cửa hàng khác nhau trong hệ thống đối tác Utop tại Việt Nam.</p>
  <p>Đây là mạng lưới được xây dựng dựa trên nền tảng Blockchain – Akachain, đảm bảo đem tới sự bảo mật tuyệt đối cũng như tối ưu hóa trong tốc độ giao dịch của đối tác và khách hàng.</p>
</div>