routes/admin.php
<?php
/*
|--------------------------------------------------------------------------
| Web Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
Route::group([
    'prefix' => 'auth',
    'as'     => 'auth.',
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('postlogin');
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::post('password/reset', 'ForgotPasswordController@reset')->name('password.update');

    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register')->name('postregister');

});

Route::group([
    'middleware' => 'auth.admin',
], function () {
    Route::get('/', function () {
        return redirect()->route('admin.home');
    });

    Route::get('/home', function () {
        return view('admin.home');
    })->name('home');

    Route::group(
        [
            'prefix' => 'image',
            'as'     => 'image.',
        ],
        function () {
            Route::post('uploadmultiple/{type?}', 'ImageController@uploadImageMultiple')->name('uploadmultiple');
            Route::post('uploadone/{type?}', 'ImageController@uploadImageOne')->name('uploadone');
            Route::post('removebysrc', 'ImageController@removeBySrc')->name('removebysrc');
        }
    );

    Route::group(
        [
            'prefix'     => 'blogcategory',
            'as'         => 'blogcategory.',
            'middleware' => ['permission:blog-category-control'],
        ],
        function () {
            Route::get('index', 'BlogCategoryController@index')->name('index');
            Route::get('show/{id}', 'BlogCategoryController@show')->name('show');
            Route::get('create', 'BlogCategoryController@create')->name('create');
            Route::post('store', 'BlogCategoryController@store')->name('store');
            Route::get('edit/{id}', 'BlogCategoryController@edit')->name('edit');
            Route::put('update/{id}', 'BlogCategoryController@update')->name('update');
            Route::delete('destroy/{id}', 'BlogCategoryController@destroy')->name('destroy');
            Route::put('restore/{id}', 'BlogCategoryController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix' => 'blogbanner',
            'as'     => 'blogbanner.',
        ],
        function () {
            Route::post('update_position','BlogBannerController@updatePosition')->name('update_position');
            Route::get('index', 'BlogBannerController@index')->name('index');
            Route::get('show/{id}', 'BlogBannerController@show')->name('show');
            Route::get('create', 'BlogBannerController@create')->name('create');
            Route::post('store', 'BlogBannerController@store')->name('store');
            Route::get('edit/{id}', 'BlogBannerController@edit')->name('edit');
            Route::put('update/{id}', 'BlogBannerController@update')->name('update');
            Route::delete('destroy/{id}', 'BlogBannerController@destroy')->name('destroy');
            Route::put('restore/{id}', 'BlogBannerController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix' => 'blog',
            'as'     => 'blog.',
        ],
        function () {
            Route::get('index', 'BlogController@index')->name('index')->middleware('permission:blog-show');
            Route::get('show/{id}', 'BlogController@show')->name('show')->middleware('permission:blog-show');
            Route::get('create', 'BlogController@create')->name('create')->middleware('permission:blog-create');
            Route::post('store', 'BlogController@store')->name('store')->middleware('permission:blog-create');
            Route::get('edit/{id}', 'BlogController@edit')->name('edit')->middleware('permission:blog-edit');
            Route::put('update/{id}', 'BlogController@update')->name('update')->middleware('permission:blog-edit');
            Route::delete('destroy/{id}', 'BlogController@destroy')->name('destroy')->middleware('permission:blog-remove');
            Route::put('restore/{id}', 'BlogController@restore')->name('restore')->middleware('permission:blog-remove');
        }
    );

    Route::group(
        [
            'prefix'     => 'productcategory',
            'as'         => 'productcategory.',
            'middleware' => ['permission:product-category-control'],
        ],
        function () {
            Route::get('index', 'ProductCategoryController@index')->name('index');
            Route::get('show/{id}', 'ProductCategoryController@show')->name('show');
            Route::get('create', 'ProductCategoryController@create')->name('create');
            Route::post('store', 'ProductCategoryController@store')->name('store');
            Route::get('edit/{id}', 'ProductCategoryController@edit')->name('edit');
            Route::put('update/{id}', 'ProductCategoryController@update')->name('update');
            Route::delete('destroy/{id}', 'ProductCategoryController@destroy')->name('destroy');
            Route::put('restore/{id}', 'ProductCategoryController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix' => 'product',
            'as'     => 'product.',
        ],
        function () {
            Route::get('index', 'ProductController@index')->name('index')->middleware('permission:product-show');
            Route::get('show/{id}', 'ProductController@show')->name('show')->middleware('permission:product-show');
            Route::get('create', 'ProductController@create')->name('create')->middleware('permission:product-create');
            Route::post('store', 'ProductController@store')->name('store')->middleware('permission:product-create');
            Route::get('edit/{id}', 'ProductController@edit')->name('edit')->middleware('permission:product-edit');
            Route::put('update/{id}', 'ProductController@update')->name('update')->middleware('permission:product-edit');
            Route::delete('destroy/{id}', 'ProductController@destroy')->name('destroy')->middleware('permission:product-remove');
            Route::put('restore/{id}', 'ProductController@restore')->name('restore')->middleware('permission:product-remove');
        }
    );

    Route::group(
        [
            'prefix' => 'slider',
            'as'     => 'slider.',
        ],
        function () {
            Route::post('update_position','SliderController@updatePosition')->name('update_position');
            Route::get('index', 'SliderController@index')->name('index');
            Route::get('show/{id}', 'SliderController@show')->name('show');
            Route::get('create', 'SliderController@create')->name('create');
            Route::post('store', 'SliderController@store')->name('store');
            Route::get('edit/{id}', 'SliderController@edit')->name('edit');
            Route::put('update/{id}', 'SliderController@update')->name('update');
            Route::delete('destroy/{id}', 'SliderController@destroy')->name('destroy');
            Route::put('restore/{id}', 'SliderController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix'     => 'user',
            'as'         => 'user.',
            'middleware' => ['permission:user-control'],
        ],
        function () {
            Route::get('index', 'UserController@index')->name('index');
            Route::get('show/{id}', 'UserController@show')->name('show');
            Route::get('create', 'UserController@create')->name('create');
            Route::post('store', 'UserController@store')->name('store');
            Route::get('edit/{id}', 'UserController@edit')->name('edit');
            Route::get('edit-permission/{id}', 'UserController@editPermission')->name('edit_permission');
            Route::put('update-permission/{id}', 'UserController@updatePermission')->name('update_permission');
            Route::put('update/{id}', 'UserController@update')->name('update');
            Route::delete('destroy/{id}', 'UserController@destroy')->name('destroy');
            Route::put('restore/{id}', 'UserController@restore')->name('restore');
            Route::put('approve/{id}', 'UserController@approve')->name('approve');
        }
    );


    Route::group(
        [
            'prefix'     => 'brandcategory',
            'as'         => 'brandcategory.',
        ],
        function () {
            Route::get('index', 'BrandCategoryController@index')->name('index');
            Route::get('show/{id}', 'BrandCategoryController@show')->name('show');
            Route::get('create', 'BrandCategoryController@create')->name('create');
            Route::post('store', 'BrandCategoryController@store')->name('store');
            Route::get('edit/{id}', 'BrandCategoryController@edit')->name('edit');
            Route::put('update/{id}', 'BrandCategoryController@update')->name('update');
            Route::delete('destroy/{id}', 'BrandCategoryController@destroy')->name('destroy');
            Route::put('restore/{id}', 'BrandCategoryController@restore')->name('restore');
        }
    );

    Route::group(
        [
            'prefix' => 'brand',
            'as'     => 'brand.',
        ],
        function () {
            Route::get('index', 'BrandController@index')->name('index');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('error/{code}', function ($code) {
    return view('errors.error', compact('code'));
})->name('error');

Route::group([
	'as' =>'user.',
    'namespace' => 'User',
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('doanh-nghiep', 'HomeController@business')->name('business');
    Route::get('ve-chung-toi', 'HomeController@aboutus')->name('aboutus');
    Route::get('faq', 'HomeController@faq')->name('faq');
    Route::get('lien-he', 'HomeController@contact')->name('contact');
    Route::post('lien-he/{type}', 'HomeController@submitContact')->name('submitContact');
    Route::get('blog', 'HomeController@blog')->name('blog');
    Route::get('blog/article/{slug}_{id}', 'HomeController@blogDetail')->name('blog.detail');
    Route::get('blog/category/{slug}_{id}', 'HomeController@blogCategory')->name('blog.category');
});

app/Models/Blog.php
<?php

namespace App\Models;

use App\Models\BaseModel;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class Blog extends BaseModel
{
    use SoftDeletes;

    protected $fillable = [
        'blog_category_id',
        'title',
        'slug',
        'content',
        'public_at',
        'status',
        'tags',
        'popular',
    ];

    protected $appends = [
        'status_text','image_frist'
    ];

    public function setTagsAttribute($value)
    {
        $this->attributes['tags'] = "," . $value . ",";
    }

    public function getTagsAttribute()
    {
        return rtrim(ltrim($this->attributes['tags'], ','), ',');
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug']  = str_slug($value);
    }

    public function getStatusTextAttribute()
    {
        return $this->status == 2 ? "Hide" : "Show";
    }

    public function getPopularTextAttribute()
    {
        return $this->popular == 1 ? "No" : "Yes";
    }

    public function getPublicAtShowAttribute()
    {
        return date("d-m-Y", strtotime($this->public_at));
    }

    public function setPublicAtAttribute($value)
    {
        $this->attributes['public_at'] = Carbon::parse($value);
    }

    public function getImageFirstAttribute()
    {
        return $this->images->where('status',2)->first()->src;
    }

    public function images()
    {
        return $this->morphMany(Images::class, 'imagetable');
    }

    public function category()
    {
        return $this->belongsTo('App\Models\BlogCategory', 'blog_category_id');
    }

    public function scopeSearchTags($query, $tags = [])
    {
        if (is_array($tags)) {
            foreach ($tags as $tag) {
                $query->orWhere('tags', 'like', '%,' . $tag . ".%");
            }
        }
    }

    public function scopeGetPopular($query)
    {
        return $query->wherePopular(2);
    }

    public function scopeUserGetList($query)
    {
        return $query->whereStatus(1)
        ->whereDate('public_at', '<=', Carbon::now())
        ->orderBy('public_at', 'DESC');
    }
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\BlogRequest;
use App\Services\BlogCategoryService;
use App\Services\BlogService;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    protected $blogService;
    protected $blogCategoryService;

    public function __construct(BlogService $blogService, BlogCategoryService $blogCategoryService)
    {
        $this->blogService         = $blogService;
        $this->blogCategoryService = $blogCategoryService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = $this->blogService->getList(true);
        return view('admin.blog.blog.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = $this->blogCategoryService->getListOnlyChildren();
        return view('admin.blog.blog.form', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogRequest $request)
    {
        $this->blogService->storeOrUpdate($request->all());
        return redirect()->route('admin.blog.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = $this->blogService->findById($id);
        return view('admin.blog.blog.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog       = $this->blogService->findById($id);
        $categories = $this->blogCategoryService->getListOnlyChildren();
        return view('admin.blog.blog.form', compact('categories', 'blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogRequest $request, $id)
    {
        $this->blogService->storeOrUpdate($request->all(), $id);
        return redirect()->route('admin.blog.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->blogService->destroyById($id);
        return redirect()->route('admin.blog.index');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {   
        $this->blogService->restoreById($id);
        return redirect()->route('admin.blog.index');
    }
}

resources/views/admin/blog/blog/form.blade.php
@extends('admin.layout.master',[
    'title'=> isset($blog->title) ? 'Update Blog '.$blog->title : 'Create Blog',
    'breadcrumb'=>[
        [
            'name' => 'Blog',
            'src' => route('admin.blog.index')
        ],
        [
            'name' => isset($blog->title) ? 'Update Blog '.$blog->title : 'Create Blog'
        ]
    ]
    ])
@section('content')
<form action="{{isset($blog->id) ? route('admin.blog.update',['id'=>$blog->id]) : route('admin.blog.store')}}" method="POST">
@csrf
@isset($blog->id)
    @method('PUT')
@endisset
<div class="row col-lg-12">
    <div class="col-lg-8">
        <div class="grid">
            <p class="grid-header">
                {{isset($blog->title) ? 'Update Blog '.$blog->title : 'Create Blog'}}
            </p>
            <div class="grid-body">
                <div class="item-wrapper">
                    <div class="row mb-3">
                        <div class="col-md-12 mx-auto">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="form-group row showcase_row_area">
                                <div class="col-md-3 showcase_text_area">
                                    <label for="inputType13">
                                        Category List
                                        <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-md-9 showcase_content_area">
                                    <div class="form-group">
                                        <select class="form-control" id="js-select-example" name="blog_category_id">
                                            <option value="">Choose blog category</option>
                                            @foreach($categories as $key => $value)
                                                <option value="{{$value['id']}}" {{old('blog_category_id', $blog->blog_category_id ?? 0) == $value['id'] ? 'selected' : ''}}>
                                                    {{$value['name']}}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 mx-auto">
                            <div class="form-group row showcase_row_area">
                                <div class="col-md-3 showcase_text_area">
                                    <label for="inputPubicAt">
                                        Public at
                                    </label>
                                </div>
                                <div class="col-md-9 showcase_content_area">
                                    <input class="form-control" id="inputPubicAt" name="public_at" type="date" value="{{HelperAdmin::timeNowOrOld(old('public_at',$blog->public_at ?? null))}}" placeholder="Public at" />
                                </div>
                            </div>
                            <div class="form-group row showcase_row_area">
                                <div class="col-md-3 showcase_text_area">
                                    <label for="inputTitle">
                                        Title
                                        <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-md-9 showcase_content_area">
                                    <input class="form-control" id="inputTitle" name="title" type="text" value="{{old('title',$blog->title ?? '')}}" placeholder="Blog Title" />
                                </div>
                            </div>
                            <div class="form-group row showcase_row_area">
                                <div class="col-md-3 showcase_text_area">
                                    <label for="inputContent">
                                        Content
                                        <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-md-9 showcase_content_area">
                                    <textarea name="content" id="textarea_ckediter" rows="10" cols="80">{!! old('content',$blog->content ?? '') !!}</textarea>
                                </div>
                            </div>
                            <div class="form-group row showcase_row_area">
                                <div class="col-md-3 showcase_text_area">
                                    <label for="inputType12">
                                        Tags
                                    </label>
                                </div>
                                <div class="col-md-9 showcase_content_area mb-0">
                                    <input class="form-control" data-role="tagsinput" type="text" name="tags" value="{{old('tags',$blog->tags ?? '')}}" placeholder="Tags" />
                                </div>
                            </div>
                            <div class="row showcase_row_area">
                                <div class="col-md-3 showcase_text_area">
                                    <label>
                                        Popular
                                    </label>
                                </div>
                                <div class="col-md-9 showcase_content_area">
                                    <div class="form-group">
                                        <div class="checkbox">
                                            <label>
                                                <input class="form-check-input" type="checkbox" name="popular" value="2" {{old('popular',$blog->popular ?? null) == '2' ? 'checked' : '' }} >
                                                    Popular
                                                    <i class="input-frame"></i>
                                                </input>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row showcase_row_area">
                                <div class="col-md-3 showcase_text_area">
                                    <label>
                                        Status
                                    </label>
                                </div>
                                <div class="col-md-9 showcase_content_area">
                                    <div class="form-group">
                                        <div class="checkbox">
                                            <label>
                                                <input class="form-check-input" type="checkbox" name="status" value="2" {{old('status',$blog->status ?? null) == '2' ? 'checked' : '' }} >
                                                    Hidden
                                                    <i class="input-frame"></i>
                                                </input>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @php
        $dataImage = old('file_uploads',isset($blog->images) ? $blog->images()->select(['src','status','id'])->get()->toArray() : [] );
    @endphp
    @include('admin.accessory.uploadMultiple',['dataImage'=>$dataImage])
</div>
</form>
@stop
@section('script')
<script src="/adstyle/js/imagemultiplehandle.js"></script>
<script>
CKEDITOR.replace('textarea_ckediter',options);
</script>
@stop

resources/views/admin/blog/blog/show.blade.php
@extends('admin.layout.master',['title'=>$blog->title.' | Blog'])
@section('content')
<div class="col-lg-12">
    <div class="grid">
        <p class="grid-header"> Information Blog </p>
        <div class="row">
            <div class="col-lg-9 equel-grid">
                <div class="grid">
                    <div class="grid-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <h4 class="card-title">
                                Title : {{$blog->title}}
                            </h4>
                            <div class="fc-right">
                                @can('blog-edit')
                                    <a href="{{route('admin.blog.edit',['id'=>$blog->id])}}" class="btn btn-info btn-sm">
                                        Edit
                                    </a>
                                @endcan
                                @can('blog-remove')
                                    <button class="btn btn-danger btn-sm" id="destroyItem" onclick="deleteByIdModal('{{$blog->id}}','{{route('admin.blog.destroy',['id'=>$blog->id])}}')">
                                        Delete
                                    </button>
                                @endcan
                            </div>
                        </div>
                        <div class="event-list-wrapper">
                            <div class="event-list">
                                <div class="item-wrapper demo-wrapper">{!!HelperAdmin::showTags($blog->tags)!!}</div>
                            </div>
                            <div class="event-list">
                                Public at : {{HelperAdmin::showTime($blog->public_at)}}
                            </div>
                            <div class="event-list">
                                <p class="event-text">
                                    Blog Category : {{$blog->category->name ?? 'Error Data'}}
                                </p>
                            </div>
                            <div class="event-list">
                                <p class="event-text">
                                    Popular : {{$blog->popular_text}}
                                </p>
                            </div>
                            <div class="event-list">
                                <p class="event-text">
                                    Status : {{$blog->status_text}}
                                </p>
                            </div>
                            <div>
                                <p>Content : </p>
                                <br>
                                <p>{!! nl2br($blog->content) !!}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 ">
                <div class="grid">
                    <div class="grid-body">
                        <section class="hk-sec-wrapper hk-gallery-wrap">
                            <div class="tab-content">
                                <div class="tab-pane fade show active" role="tabpanel">
                                    <h6 class="mt-30 mb-20 ml-20">Gallery</h6>
                                    <div class="row hk-gallery">
                                        @foreach($blog->images as $keyImage => $valueImage)
                                            <div class="{{$valueImage->status == 2 ? 'col-lg-12' : 'col-lg-6' }} col-md-4" data-src="{{url($valueImage['src'])}}">
                                                <a class="" href="#">
                                                    <div class="gallery-img" style="background-image:url('{{url($valueImage['src'])}}');">
                                                    </div>
                                                </a>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('css')
<link href="/adstyle/vendors/lightgallery/css/lightgallery.min.css" rel="stylesheet" type="text/css">
@stop
@section('script')
<script src="/adstyle/vendors/lightgallery/js/lightgallery-all.min.js"></script>
<script>
    $('.hk-gallery').lightGallery({  showThumbByDefault: false,hash: false});
</script>
@stop

@section('modal')
    @can('blog-remove')
        @include('admin.layout.include.deleteModal')
    @endcan
@stop